version: '3'
services:
  db:
    image: 'mysql:5.7'
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    command:
      - --character-set-server=utf8 
      - --collation-server=utf8_general_ci
    ports:
      - "3306:3306"
    env_file:
      - docker.env
volumes:
  mysql_data: